version: "3.9"
services:
  db:
    image: mongo:4.2
    restart: always
    container_name: six-cities_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASWORD}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - six-cities_data:/data/db

  db_ui:
    image: mongo-express:latest
    restart: always
    container_name: six-cities_mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${ME_CONFIG_MONGODB_ADMINUSERNAME}:${ME_CONFIG_MONGODB_ADMINPASSWORD}@db:${DB_PORT}/

volumes:
  six-cities_data:
